version: "3"
services:
  # REACT APP ////////////////////////////////
  react-app:
    image: react-app-production
    restart: unless-stopped
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app

  # SERVER ////////////////////////////////
  api-server:
    image: api-server-production
    restart: unless-stopped
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
